(function(){const premiumStyles=document.createElement('link');premiumStyles.rel='stylesheet';premiumStyles.href='/planes/premium.css';document.head.append(premiumStyles);
const clp=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced)document.body.animate([{opacity:.94},{opacity:1}],{duration:180,easing:'ease-out'});
document.documentElement.classList.add('motion-ready');
const header=document.querySelector('.top');addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>12),{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('in-view');observer.unobserve(entry.target)}),{threshold:.12});
document.querySelectorAll('.section-title,.card,.tiers article,.calculator>div,.benefits>div,.company-form>div,.company-form form,.privacy>* ,.stats article,.fleet-list').forEach((el,i)=>{el.classList.add('motion-item');el.style.setProperty('--delay',`${Math.min(i%4,3)*70}ms`);observer.observe(el)});
const rows=['Registro completo del vehículo','PPU + VIN + chasis','Ingreso a base SKANO','Detectable por lectores SKANO','Publicación web pública','Recompensa','Alertas al propietario','Correos por detección','Historial de detecciones','Información de recuperación','Información de comisaría','Seguimiento activo'];
const body=document.querySelector('#comparison');if(body)body.innerHTML=rows.map((x,i)=>`<tr><td>${x}</td><td>${i<4?'✓':'—'}</td><td>✓</td><td>✓</td></tr>`).join('');
const animateValue=(el,to)=>{if(reduced){el.textContent=clp(to);return}const from=Number(el.dataset.value)||0,start=performance.now(),duration=320;el.dataset.value=to;const tick=now=>{const p=Math.min(1,(now-start)/duration),ease=1-Math.pow(1-p,3);el.textContent=clp(Math.round(from+(to-from)*ease));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)};
document.querySelectorAll('.price b').forEach(el=>{const value=Number(el.textContent.replace(/\D/g,''));if(!value)return;const o=new IntersectionObserver(es=>{if(es[0].isIntersecting){const original=el.textContent;el.textContent='$0';let start=performance.now();const tick=now=>{const p=Math.min(1,(now-start)/650);el.textContent='$'+Math.round(value*(1-Math.pow(1-p,3))).toLocaleString('es-CL');if(p<1&&!reduced)requestAnimationFrame(tick);else el.textContent=original};tick(start);o.disconnect()}},{threshold:.7});o.observe(el)});
const input=document.querySelector('#fleetCount');if(input){let lastTier='';const render=()=>{const n=Math.max(1,Number(input.value)||1);input.value=n;const t=n>=20?['20 o más vehículos',10990,'business_20_plus']:n>=6?['6 a 19 vehículos',13000,'business_6_19']:['1 a 5 vehículos',16990,'business_1_5'];const result=document.querySelector('.result');if(lastTier&&lastTier!==t[2]){result.classList.remove('tier-changed');void result.offsetWidth;result.classList.add('tier-changed')}lastTier=t[2];document.querySelector('#tierName').textContent=t[0];document.querySelector('#qty').textContent=n;document.querySelector('#unitPrice').textContent=clp(t[1]);animateValue(document.querySelector('#total'),n*t[1]);document.querySelector('#businessCheckout').href=`/checkout/?checkoutType=business&vehicleCount=${n}&pricePerVehicle=${t[1]}&monthlyTotal=${n*t[1]}&planTier=${t[2]}`};input.addEventListener('input',render);document.querySelector('#minus').onclick=()=>{input.value=Math.max(1,+input.value-1);render()};document.querySelector('#plus').onclick=()=>{input.value=+input.value+1;render()};render()}
const searchButton=document.querySelector('.vehicle-search button');searchButton?.addEventListener('click',()=>{const form=searchButton.closest('form');form.classList.remove('scanning');void form.offsetWidth;form.classList.add('scanning');searchButton.textContent='ESCANEANDO';setTimeout(()=>{searchButton.textContent='BUSCAR';form.classList.remove('scanning')},reduced?50:900)});
const out=document.querySelector('#checkoutSummary');if(out){const q=new URLSearchParams(location.search);const business=q.get('checkoutType')==='business';document.querySelector('#checkoutType').textContent=`checkoutType = ${business?'business':'individual'}`;if(business)out.innerHTML=`<dl><div><dt>Plan</dt><dd>${q.get('planTier')}</dd></div><div><dt>Vehículos</dt><dd>${q.get('vehicleCount')}</dd></div><div><dt>Precio por vehículo</dt><dd>${clp(+q.get('pricePerVehicle'))}</dd></div><div><dt>Total mensual</dt><dd>${clp(+q.get('monthlyTotal'))}</dd></div></dl>`}
})();
